name: "Amul Protein Products Notifier"
on:
  workflow_dispatch:

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v5
              with:
                fetch-depth: 1
            
            - name: "install dependencies"
              run: |
                pip install -r requirements.txt
                playwright install chromium

            - name: "Run Notifier Script"
              run: |
                python src/main.py
              env:
                BARK_API_TOKENS: ${{ secrets.BARK_API_TOKENS }}
            
            - name: "Upload traces"
              uses: actions/upload-artifact@v4
              with:
                name: trace.zip
                path: trace.zip
                retention-days: 1
